//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int mssv { get; set; }
        public string name { get; set; }
        public int birthday { get; set; }
        public string phone { get; set; }
        public int sex { get; set; }
        public string address { get; set; }
        public string email { get; set; }
    }
}
